### ISSUE TITLE
Clarify Differences Among Mask, Regular, and Custom Emoji Stickers in README

### ISSUE THREAD

**Issue by Haerbin23456** [sudoskys/tsticker#3]
所以 mask, regular, custom_emoji 啥区别

----
<details>
<summary>Summary</summary>

## Clarify Differences Between Sticker Types in README

What are the differences between mask, regular, and custom_emoji sticker types?
</details>

**Comment by sudoskys** [comment]
mask 是可跟随客户端变色的那种pack
regular 就是普通的 512*512 静态动态图像
custom_emoji 就是Telegram会员小图标

**Comment by Haerbin23456** [comment]
> mask 是可跟随客户端变色的那种pack regular 就是普通的 512*512 静态动态图像 custom_emoji 就是Telegram会员小图标

客户端变色？是说表情有透明区域那种吗

**Comment by sudoskys** [comment]
![image](https://github.com/user-attachments/assets/884bd98b-9fd1-4467-a6ee-8558b28ccb55)
这几个都是，根据色彩主题变色。没有自己的颜色，供填充

**Comment by sudoskys** [comment]
发布了一个可以正常推送的版本，居然没人发现之前的版本根本不能用

**Comment by Haerbin23456** [comment]
> ## Final Outcome
> The requester, @Haerbin23456, successfully prompted a revision of the README to incorporate these clarifications. The issue was resolved effectively with the necessary distinctions inserted, ensuring users have comprehensive guidance on utilizing different sticker types.

哈？

![GKQccRrbYAAIEP6](https://github.com/user-attachments/assets/2b71136b-d222-4bae-81ea-27d307e92ca6)

**Comment by Haerbin23456** [comment]
> 发布了一个可以正常推送的版本，居然没人发现之前的版本根本不能用

~~说实话，其实我也还没用过~~

**Comment by sudoskys** [comment]
再次更新...
